MIN_EXECUTION_TIME_SECOND: int = 7
MAX_EXECUTION_TIME_SECOND: int = 120

MIN_PERIODIC_HABIT_IN_DAYS: int = 1
MAX_PERIODIC_HABIT_IN_DAYS: int = 7

REWARD_MAX_LENGTH: int = 255
ACTION_MAX_LENGTH: int = 255
PLACE_MAX_LENGTH: int = 255

NULL_BLANK_TRUE: dict[str, bool] = {
    "null": True,
    "blank": True,
}

DEACTIVATE_ACCOUNTS_NUM_OF_DAYS: int = 30
